 # Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# CompactStorage
mod_id=compact_storage
mod_name=CompactStorage
mod_description=CompactStorage adds a variety of new storage options to Minecraft, with Chests and Backpacks that scale up to 24x12 (288 items!)
mod_author=witchica
mod_website=https://witchica.com/
mod_sources=https://github.com/witchica/compact-storage
logo_file=compact_storage.png

# CompactStorage Fabric
mod_fabric_loader_minimum=>=0.16.11

# CompactStorage NeoForge
mod_neo_loader_version=[2,)
mod_neo_version=[21.0,)
mod_neo_minecraft_range=[1.21,)

# Architectury Version
architectury_version=13.0.1

# Mod properties
mod_version = 7.0
maven_group = com.witchica
archives_name = compact_storage
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.21.4

# Dependencies
architectury_api_version = 15.0.1
fabric_loader_version = 0.16.11
fabric_api_version = 0.119.2+1.21.4
neoforge_version = 21.4.9-beta
