# Mod Properties
# Recommended Versioning Scheme: https://docs.neoforged.net/docs/gettingstarted/versioning/

# Version will be version + .BUILD_ID + version_suffix, eg: if the build is 210 and suffix is 'b' = 21.11.210b
version = 21.11
version_suffix=

# Your mod id should be descriptive, ideally just your mod's name in all lowercase with no hyphens or underscores.
mod_id = compact_storage
archives_name = compactstorage

mod_name = CompactStorage

# Your group should be a unique identifier in reverse domain format.
group = com.witchica

description=CompactStorage provides new ways to store your items in a more compact way.

# Fill out these URLs with links to your website or project page, sources (if public), issue tracker and Discord invite.
homepage = https://modrinth.com/mod/compact-storage
sources = https://github.com/witchica/compact-storage
issues = https://github.com/witchica/compact-storage/issues
discord = ''

# Make sure the license here matches the one you defined in the LICENSE file.
license=GPLv3

mod_author = witchica

# Credits can include other attribution as well, such as artists, etc.
credits =12 years! Thanks to everyone who has contributed by playing the mod!

# Publishing Properties
# You can find the project ID on the CurseForge / Modrinth project page. You can leave this empty until you publish your mod.
curseforge_project_id = 0
modrinth_project_id = 0

# If you have a Maven to deploy to, configure its URLs here.
# maven_releases = https://
# maven_snapshots = https://

# Build Properties
# The Java version to use. Different Minecraft versions require different Java versions.
java_version = 21

# You can develop against published NeoForge snapshots (instead of releases) by adding the URL linked in the NeoForge PR here and updating the NeoForge version in gradle/libs.versions.toml.
neoforge_snapshot_url = 

# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
