repositories {
    maven {
        name = 'Twelve Iterations'
        url = 'https://maven.twelveiterations.com/repository/maven-public/'
        content {
            includeGroup 'net.blay09.mods'
        }
    }


    maven {
        url "https://cursemaven.com"
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
        content {
            includeGroup "mezz.jei"
        }
    }
    maven {
        name = "Nucleoid"
        url = 'https://maven.nucleoid.xyz/releases'
    }

    exclusiveContent {
        forRepository {
            maven {
                name = 'Minecraft'
                url = 'https://libraries.minecraft.net/'
            }
        }
        filter { includeGroupAndSubgroups("com.mojang") }
    }
}
