# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.
name: publish
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: 'microsoft'
          java-version: '25'
          cache: 'gradle'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew curseforge modrinth